### ISSUE TITLE
Can we get an web extension of this ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [epsylon/cintruder#8]

**Comment by epsylon** [comment]
Hi @minanagehsalalma ,
This is a good question but it is related to the scope in which was projected the whole tool, itself. This was at 2012 when only a few tools related to OCR techniques were working on the wild and one of them was a FF extension. CINtruder was developed most thinking intro provide a shell related tool, because of the need to bypass some checks when a pentesting is ongoing. At that time, when a pentester had a form with a captcha, the possibility to use other tools, such as XSSer or SQLMap was restricted. So CIntruder was deployed that way, to provide a solved captcha to the next tool... 
On the other hand, this tool is coded using Python (actually ported from 2 to 3), and this language was also selected, because no other similar exists written on it, at 2012.
My idea was to make exactly the reverse plan that you propose. Just try to "frame" website into CINtruder (Web/GUI). It sounds more inline with the init proposal. But not any work at this moment on that way..
